badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  co2-emissions:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/co2-emissions
    requirements: {}
    stages:
    - setup
    - run
    - validate
  data-science-no-stages:
    envs:
      host:
        args: []
    path: pipelines/data-science-no-stages
    stages:
    - run
    - generate-figures
    - validate
  docker-data-science:
    envs:
      host:
        args: []
    path: pipelines/docker-data-science
    stages:
    - build-docker-image
    - generate-learning-curves
    - generate-figures
    - validate
  mypipe:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/mypipe
    requirements: {}
    stages:
    - download-data
    - run-analysis
    - plot-graphs
search_sources:
- popperized
version: 1
