badge-server-url: http://badges.falsifiable.us
metadata:
  abstract: "Popper is a convention and CLI tool for conducting experiments and writing\
    \ academic articles following best OSS and DevOps practices. The open-source CLI\
    \ tool helps researchers organize all the artifacts associated to a scientific\
    \ exploration inside a code repository such as Git. These popperized\
    \ repositories are self-contained and can be easily shared (cloned via Git) so\
    \ that others can replicate the original results (see examples here)."
  access_right: open
  author1: Karen C. Tsai, ktsai.lanl@gmail.com, Los Alamos National Laboratory
  keywords: Popper, GIT, Travis-CI, Docker, Zenodo
  license: CC-BY-4.0
  publication_type: article
  title: Popper Tutorials
  upload_type: publication
pipelines:
  co2-emissions:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/co2-emissions
    requirements: {}
    stages:
    - setup
    - run
    - validate
  data-science-no-stages:
    envs:
      host:
        args: []
    path: pipelines/data-science-no-stages
    stages:
    - run
    - generate-figures
    - validate
  docker-data-science:
    envs:
      host:
        args: []
    path: pipelines/docker-data-science
    stages:
    - build-docker-image
    - generate-learning-curves
    - generate-figures
    - validate
  mypipe:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/mypipe
    requirements: {}
    stages:
    - download-data
    - run-analysis
    - plot-graphs
search_sources:
- popperized
version: 1
